language: python

python:
  - 3.5.1

cache: pip

services:
  - postgresql

before_script:
  - psql -c 'create database travis_database;' -U postgres

install:
  - make .env env=test
  - make requirements env=test

script:
  - make test-travis
