"""empty message

Revision ID: 2214cd39d437
Revises: None
Create Date: 2016-06-02 21:42:52.895060

"""

# revision identifiers, used by Alembic.
revision = '2214cd39d437'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_code',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hashkey', sa.String(length=10), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashkey'),
    sa.UniqueConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('source_code')
    ### end Alembic commands ###
